// SPDX-License-Identifier: Apache-2.0

package auth

import (
	"database/sql"
	"errors"
	"fmt"
	"time"
)

// CreateSession inserts a new session row. The id is generated by the
// caller (the cookie carries the same value in its sid claim).
func (s *SQLiteAuthStore) CreateSession(sess Session) error {
	_, err := s.db.Exec(
		`INSERT INTO sessions (id, user_id, label, ip, created_at, last_seen_at, expires_at)
		 VALUES (?, ?, ?, ?, ?, ?, ?)`,
		sess.ID, sess.UserID, sess.Label, sess.IP,
		sess.CreatedAt.UnixNano(), sess.LastSeenAt.UnixNano(), sess.ExpiresAt.UnixNano(),
	)
	if err != nil {
		return fmt.Errorf("auth: insert session: %w", err)
	}
	return nil
}

// GetSession returns a single session row by id, or ErrSessionNotFound.
func (s *SQLiteAuthStore) GetSession(id string) (Session, error) {
	var (
		sess                            Session
		createdNs, lastSeenNs, expiryNs int64
	)
	err := s.db.QueryRow(
		`SELECT id, user_id, label, ip, created_at, last_seen_at, expires_at
		   FROM sessions WHERE id = ?`,
		id,
	).Scan(&sess.ID, &sess.UserID, &sess.Label, &sess.IP, &createdNs, &lastSeenNs, &expiryNs)
	if errors.Is(err, sql.ErrNoRows) {
		return Session{}, ErrSessionNotFound
	}
	if err != nil {
		return Session{}, fmt.Errorf("auth: get session: %w", err)
	}
	sess.CreatedAt = time.Unix(0, createdNs).UTC()
	sess.LastSeenAt = time.Unix(0, lastSeenNs).UTC()
	sess.ExpiresAt = time.Unix(0, expiryNs).UTC()
	return sess, nil
}

// TouchSession updates last_seen_at. A zero-row update is intentionally
// not an error: the row may have been revoked between the middleware's
// read and this write, and the next request will reject the cookie
// anyway.
func (s *SQLiteAuthStore) TouchSession(id string, lastSeen time.Time) error {
	if _, err := s.db.Exec(
		`UPDATE sessions SET last_seen_at = ? WHERE id = ?`,
		lastSeen.UnixNano(), id,
	); err != nil {
		return fmt.Errorf("auth: touch session: %w", err)
	}
	return nil
}

// RevokeSession deletes one session scoped to its owner. Returns
// ErrSessionNotFound when nothing matched so the handler can answer 404
// rather than leaking whether the id exists under another user.
func (s *SQLiteAuthStore) RevokeSession(id, userID string) error {
	res, err := s.db.Exec(`DELETE FROM sessions WHERE id = ? AND user_id = ?`, id, userID)
	if err != nil {
		return fmt.Errorf("auth: revoke session: %w", err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("auth: rows affected: %w", err)
	}
	if n == 0 {
		return ErrSessionNotFound
	}
	return nil
}

// RevokeUserSessions deletes every session for the user, returning the
// number removed.
func (s *SQLiteAuthStore) RevokeUserSessions(userID string) (int, error) {
	res, err := s.db.Exec(`DELETE FROM sessions WHERE user_id = ?`, userID)
	if err != nil {
		return 0, fmt.Errorf("auth: revoke user sessions: %w", err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("auth: rows affected: %w", err)
	}
	return int(n), nil
}

// RevokeOtherUserSessions deletes every session for the user except
// keepID, returning the number removed. An empty keepID revokes them
// all (no row can match an empty id).
func (s *SQLiteAuthStore) RevokeOtherUserSessions(userID, keepID string) (int, error) {
	res, err := s.db.Exec(`DELETE FROM sessions WHERE user_id = ? AND id <> ?`, userID, keepID)
	if err != nil {
		return 0, fmt.Errorf("auth: revoke other user sessions: %w", err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("auth: rows affected: %w", err)
	}
	return int(n), nil
}

// ListSessions returns the user's sessions, most-recently-active first.
func (s *SQLiteAuthStore) ListSessions(userID string) ([]Session, error) {
	rows, err := s.db.Query(
		`SELECT id, user_id, label, ip, created_at, last_seen_at, expires_at
		   FROM sessions WHERE user_id = ? ORDER BY last_seen_at DESC`,
		userID,
	)
	if err != nil {
		return nil, fmt.Errorf("auth: list sessions: %w", err)
	}
	defer func() { _ = rows.Close() }()
	out := []Session{}
	for rows.Next() {
		var (
			sess                            Session
			createdNs, lastSeenNs, expiryNs int64
		)
		if err := rows.Scan(&sess.ID, &sess.UserID, &sess.Label, &sess.IP, &createdNs, &lastSeenNs, &expiryNs); err != nil {
			return nil, fmt.Errorf("auth: scan session: %w", err)
		}
		sess.CreatedAt = time.Unix(0, createdNs).UTC()
		sess.LastSeenAt = time.Unix(0, lastSeenNs).UTC()
		sess.ExpiresAt = time.Unix(0, expiryNs).UTC()
		out = append(out, sess)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("auth: rows sessions: %w", err)
	}
	return out, nil
}

// DeleteExpiredSessions prunes rows whose expires_at is at or before
// `before`, returning the count removed. Called opportunistically at
// login so stale rows don't accumulate.
func (s *SQLiteAuthStore) DeleteExpiredSessions(before time.Time) (int, error) {
	res, err := s.db.Exec(`DELETE FROM sessions WHERE expires_at <= ?`, before.UnixNano())
	if err != nil {
		return 0, fmt.Errorf("auth: delete expired sessions: %w", err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("auth: rows affected: %w", err)
	}
	return int(n), nil
}
